project:
  type: website

website:
  title: "Travel Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shaggycamel/travel_blog
      - icon: instagram
        href: https://www.instagram.com/shaggy.camel/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

